### ISSUE TITLE
Holding 'p' key pressed leads to an uncontrollable state

### ISSUE THREAD

**Issue by elpinal** [itchyny/bed#10]
First, copying something by `y` command in visual mode.

Second, holding `p` key pressed to paste the copied text repeatedly.

Then, the `bed` program hangs up before long.

**Comment by itchyny** [comment]
Yeah, this is what I found last night but could not find where it stucks.

**Comment by itchyny** [comment]
This should be much better with 291f0dad15a7fc79ab920fab64862dc6f6381af1, but there still seem to be some deadlock somewhere :(

**Comment by itchyny** [comment]
The problem is somehow resolved for now so I close the issue (c9bb5070b6b74e10ea0d497b1c405dd9325079c4 is probably related).
