### ISSUE TITLE
Backspace in replace mode: Is it desired behavior?

### ISSUE THREAD

**Issue by elpinal** [itchyny/bed#12]
As it is, in replace mode, backspace can delete bytes which exist before entering replace mode.
It is clearly different from Vim.
Moreover, it may be frustrating to partially undo replacing.

**Comment by itchyny** [comment]
Of course no, it's a kind of unimplemented feature rather than a bug. It seems that there're some other issues with the replace mode.

**Comment by elpinal** [comment]
OK, I'll fix it if time permits.
