### ISSUE TITLE
Move cursor in previous/next line

### ISSUE THREAD

**Issue by fxha** [itchyny/bed#16]
Thanks for the great work!

I didn't see this on the roadmap, so it would be a nice feature if the cursor automatically moves in the previous/next line if the cursor in on the left or right side.

E.g. Cursor at `0/b` + press `→`/`L` should jump to `0c/0` and not stuck at the same place.

![bed_arrow](https://user-images.githubusercontent.com/22716132/39662913-cc4a4be0-5069-11e8-808c-c4eb0ac344d0.png)

**Comment by itchyny** [comment]
This is an intended behavior because the arrow keys behaves like this in Vim. You can use `w` / `b` or `space` / `backspace` to move the cursor wrapping the lines.

**Comment by fxha** [comment]
OK, then I found another problem: `space` and `backspace` are not working on Linux. I close this, because arrow keys work as expected.

**Comment by itchyny** [comment]
Oops, I noticed it was not implemented. I implemented in 420722209d957f5bb85c63bd6df68fb65631e74f.
