### ISSUE TITLE
Can't search beyond currently loaded chunk?

### ISSUE THREAD

**Issue by moshee** [itchyny/bed#20]
When using the search (`/`) command I can't seem to get results for any strings that aren't already visible on the screen. If I scroll down to where a string becomes visible, then hitting 'n' will then jump to it, but if it's not on the screen, 'n' will do nothing. Is this correct?

**Comment by itchyny** [comment]
Yes, I agree it's not a good behavior. I'm thinking of implementing a asynchronous search as listed in #1, not to block the user's cursor motion. Create a new goroutine to search around the file and feedback to the main goroutine when the text is found.

**Comment by itchyny** [comment]
This is implemented in ccab6b84bab0b353bb903a1b8aa036a21450e1f7.
