### ISSUE TITLE
Quit after undo

### ISSUE THREAD

**Issue by Zarathustra2** [itchyny/bed#27]
Minor bug

Since #25 users cannot leave the editor with **:q** if they have unsaved changes.

If I edit a file but **undo** it till the state I opened the file, I am still forced to quit with **:q!** even though there are no changes. 

I think this could be solved if for the file maybe a hash would be saved of the last saved state. 
But I am not sure if this is the best way to solve this minor problem.

**Comment by itchyny** [comment]
Ah, ok. I'll fix this in a few days.

**Comment by itchyny** [comment]
Sorry for keeping this open for months, this is now fixed.
