### ISSUE TITLE
Where all the colors?

### ISSUE THREAD

**Issue by abitrolly** [itchyny/bed#31]
Some editors look like this.

![image](https://user-images.githubusercontent.com/8781107/82181320-f77aa280-98ea-11ea-9884-fc5fa1221343.png)

Or even this,

![image](https://user-images.githubusercontent.com/8781107/82181370-0e20f980-98eb-11ea-971e-de7e670a053f.png)

**Comment by itchyny** [comment]
The bed command does not support this kind of coloring because it makes difficult to make it visible for both light and dark terminals. The issue report is unclear for what is expected, so closing.

**Comment by abitrolly** [comment]
@itchyny how does `vim` and `oh-my-zsh` handle this then? Do you use any syntax highlighting in terminal?

**Comment by itchyny** [comment]
Some terminal tools have color themes feature, but I don't implement it in the bed command because that's not what I want to put effort to. Actually bed already uses [light green color](https://github.com/itchyny/bed/blob/be48539015ed0de0bc5064930266a6a1bc55dc93/tui/tui_window.go#L101) but I should minimize the use of colors, it is a thorny road.

**Comment by abitrolly** [comment]
Why not to use "logical" color which can be painted according to palette specified in command line param?

**Comment by itchyny** [comment]
Your comments so far do not describe how you expect the hexes to be colored, what you need them for. In any cases, my current answer is I don't implement such colors because I don't need them and I want to keep the command simple as it is. If you want such colors, use different tools, thanks.

**Comment by abitrolly** [comment]
@itchyny you didn't answer why you are not using discolored terminal either. :D

If you take a look at `hexedit` output, the coloring scheme separates hexes into four zones.
1. (red) 00 - zeroes
2. (grn) 01-1F - unprintable control characters
3. (wht) 20-7F - lower, safe part of ASCII table
4. (blu) 80-FF - higher part of ASCII table

The other editor uses colors to segment working areas.
