### ISSUE TITLE
support opening from STDIN

### ISSUE THREAD

**Issue by naikrovek** [itchyny/bed#36]
Running something then viewing the output in `bed` seems very useful, to me.

If you feel like working on this any more, adding that would be lovely.  If I add that support, I will create a pull request for it.  Please feel no obligation to implement this if you don't want to.  You owe us _nothing_.  (I just want to be clear about that.)

This is a useful little tool.  Thank you!

**Comment by itchyny** [comment]
The standard input is not seekable, so we cannot implement this efficiently. We have to read the entire stream on the memory (may fail due when huge data is piped). What happens on `bed < /dev/random`?

**Comment by itchyny** [comment]
The standard input is not seekable, so we cannot implement this efficiently. We have to read the entire stream on the memory (may fail due when huge data is passed). What happens on `bed < /dev/random`?

**Comment by naikrovek** [comment]
I get a single null byte and nothing else.

How does `xxd` do this?  It must deal with the data as it comes in, never holding much at once or something like that.  STDIN to STDOUT is easier than STDIN to memory buffer.  

ok.

**Comment by itchyny** [comment]
The binary editor allows the user to scroll down and up the target file, but it is not possible with STDIN. `xxd` just converts its fixed size buffer and print to STDOUT. We cannot find the end of the buffer on pressing <kbd>G</kbd> when STDIN has infinite size like `bed < /dev/random`, and also we have to keep the entire data on memory to allow navigating to the start on pressing <kbd>gg</kbd>.

**Comment by itchyny** [comment]
I'm thinking of implementing this feature but may take a few weeks. The less command works well for the situation, it reads what it needs, while it keeps all data on the memory. We can scroll both down and up with `xxd /dev/random | less`, and `G` hangs. Although `bed` have to know the total size of the buffer for the status line and the scroll bar.

**Comment by itchyny** [comment]
I implemented this feature, please try.

**Comment by naikrovek** [comment]
It works.  I didn't try opening /dev/urandom because I don't need to open files like that, but piping normal stuff in to `bed` works great.  thank you!
